version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$PASSWORD
      - POSTGRES_USER=$USER
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABSE
      - DB_PORT=$DB_DOCKER_PORT
    links:
      - db    
volumes: 
  db: